### ISSUE TITLE
关于您的网站的字体

### ISSUE THREAD

**Issue by xwwwb** [ruhuang2001/ruhuang2001.github.io#1]
字体挺好看的，请问您用的是哪一个字体呀？

**Comment by ruhuang2001** [comment]
我的是Gridea搭建的，主题是https://github.com/hsxyhao/gridea-theme-next。
然后在Gridea中的外观选Gemini

**Comment by ruhuang2001** [comment]
@xwwwb 我的是Gridea搭建的，主题是https://github.com/hsxyhao/gridea-theme-next
然后在Gridea中的外观选Gemini，字体不清楚（我看看代码里面有没有信息吧）

**Comment by ruhuang2001** [comment]
@xwwwb 我刚刚查了下，好像是这样的：
> 非代码字体：回退到"PingFang SC", "Microsoft YaHei", sans-serif
> 代码字体：回退到consolas, Menlo, "PingFang SC", "Microsoft YaHei", monospace(等宽)

可以试试

**Comment by xwwwb** [comment]
原来是next的修改版主题，我说看着怎么和next一样呢😂😂
我的博客xwwwb.com

**Comment by ruhuang2001** [comment]
哇你从高中就开始写博客了吗？19级的我太菜了，最近才开始弄这个，而且还不知道写啥:neutral_face:

**Comment by xwwwb** [comment]
我也差不多半年一篇😂😂
